#sitio web wordpress
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-backend
  template:
    metadata:
      labels:
        app: db-backend
    spec:
      containers:
      - name: db-backend
        image: esteban107/repodocker107:mysqldevelopv1
        env:
#        - name: MYSQL_DATABASE
#          value: "tutorial_crud"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"
        resources:
          limits:
            memory: "500Mi"
            cpu: "1500m"
        ports:
        - containerPort: 3306


---
apiVersion: v1
kind: Service
metadata:
  name: db-backend
spec:
  ports:
  - port: 3306
  selector:
    app: db-backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server-front
  strategy:
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  minReadySeconds: 5    
  template:
    metadata:
      labels:
        app: web-server-front
    spec:
      containers:
      - name: web-server-front
        image: esteban107/crudphp:latest
        env:
        - name: CRUD_DB_HOST
          value: "db-backend"
        - name: CRUD_DB_USER
          value: "admin"
        - name: CRUD_DB_PASSWORD
          value: "admin"
        - name: CRUD_DB_NAME
          value: "tutorial_crud"  
        - name: CRUD_TABLE_PREFIX
          value: "CRUD"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-front
spec:
  type: LoadBalancer
  selector:
    app: web-server-front
  ports:
  - port: 80
    targetPort: 80

